// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_details.proto
// Protobuf Java Version: 4.26.1

package proto;

public final class UserDetailsOuterClass {
  private UserDetailsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      UserDetailsOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.UserDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 accountNumber = 1;</code>
     * @return The accountNumber.
     */
    int getAccountNumber();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string dob = 4;</code>
     * @return The dob.
     */
    java.lang.String getDob();
    /**
     * <code>string dob = 4;</code>
     * @return The bytes for dob.
     */
    com.google.protobuf.ByteString
        getDobBytes();

    /**
     * <code>string email = 5;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 5;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string accountType = 6;</code>
     * @return The accountType.
     */
    java.lang.String getAccountType();
    /**
     * <code>string accountType = 6;</code>
     * @return The bytes for accountType.
     */
    com.google.protobuf.ByteString
        getAccountTypeBytes();

    /**
     * <code>double accountSavings = 7;</code>
     * @return The accountSavings.
     */
    double getAccountSavings();
  }
  /**
   * Protobuf type {@code proto.UserDetails}
   */
  public static final class UserDetails extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:proto.UserDetails)
      UserDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        UserDetails.class.getName());
    }
    // Use UserDetails.newBuilder() to construct.
    private UserDetails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserDetails() {
      name_ = "";
      address_ = "";
      dob_ = "";
      email_ = "";
      accountType_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.UserDetailsOuterClass.internal_static_proto_UserDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.UserDetailsOuterClass.internal_static_proto_UserDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.UserDetailsOuterClass.UserDetails.class, proto.UserDetailsOuterClass.UserDetails.Builder.class);
    }

    public static final int ACCOUNTNUMBER_FIELD_NUMBER = 1;
    private int accountNumber_ = 0;
    /**
     * <code>int32 accountNumber = 1;</code>
     * @return The accountNumber.
     */
    @java.lang.Override
    public int getAccountNumber() {
      return accountNumber_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOB_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dob_ = "";
    /**
     * <code>string dob = 4;</code>
     * @return The dob.
     */
    @java.lang.Override
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dob_ = s;
        return s;
      }
    }
    /**
     * <code>string dob = 4;</code>
     * @return The bytes for dob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 5;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 5;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTTYPE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object accountType_ = "";
    /**
     * <code>string accountType = 6;</code>
     * @return The accountType.
     */
    @java.lang.Override
    public java.lang.String getAccountType() {
      java.lang.Object ref = accountType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountType_ = s;
        return s;
      }
    }
    /**
     * <code>string accountType = 6;</code>
     * @return The bytes for accountType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountTypeBytes() {
      java.lang.Object ref = accountType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNTSAVINGS_FIELD_NUMBER = 7;
    private double accountSavings_ = 0D;
    /**
     * <code>double accountSavings = 7;</code>
     * @return The accountSavings.
     */
    @java.lang.Override
    public double getAccountSavings() {
      return accountSavings_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (accountNumber_ != 0) {
        output.writeInt32(1, accountNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dob_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, dob_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountType_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, accountType_);
      }
      if (java.lang.Double.doubleToRawLongBits(accountSavings_) != 0) {
        output.writeDouble(7, accountSavings_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (accountNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, accountNumber_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, address_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dob_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, dob_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(accountType_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, accountType_);
      }
      if (java.lang.Double.doubleToRawLongBits(accountSavings_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, accountSavings_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.UserDetailsOuterClass.UserDetails)) {
        return super.equals(obj);
      }
      proto.UserDetailsOuterClass.UserDetails other = (proto.UserDetailsOuterClass.UserDetails) obj;

      if (getAccountNumber()
          != other.getAccountNumber()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getDob()
          .equals(other.getDob())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getAccountType()
          .equals(other.getAccountType())) return false;
      if (java.lang.Double.doubleToLongBits(getAccountSavings())
          != java.lang.Double.doubleToLongBits(
              other.getAccountSavings())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNTNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getAccountNumber();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + DOB_FIELD_NUMBER;
      hash = (53 * hash) + getDob().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ACCOUNTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getAccountType().hashCode();
      hash = (37 * hash) + ACCOUNTSAVINGS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAccountSavings()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static proto.UserDetailsOuterClass.UserDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static proto.UserDetailsOuterClass.UserDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static proto.UserDetailsOuterClass.UserDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.UserDetailsOuterClass.UserDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.UserDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.UserDetails)
        proto.UserDetailsOuterClass.UserDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.UserDetailsOuterClass.internal_static_proto_UserDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.UserDetailsOuterClass.internal_static_proto_UserDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.UserDetailsOuterClass.UserDetails.class, proto.UserDetailsOuterClass.UserDetails.Builder.class);
      }

      // Construct using proto.UserDetailsOuterClass.UserDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        accountNumber_ = 0;
        name_ = "";
        address_ = "";
        dob_ = "";
        email_ = "";
        accountType_ = "";
        accountSavings_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.UserDetailsOuterClass.internal_static_proto_UserDetails_descriptor;
      }

      @java.lang.Override
      public proto.UserDetailsOuterClass.UserDetails getDefaultInstanceForType() {
        return proto.UserDetailsOuterClass.UserDetails.getDefaultInstance();
      }

      @java.lang.Override
      public proto.UserDetailsOuterClass.UserDetails build() {
        proto.UserDetailsOuterClass.UserDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.UserDetailsOuterClass.UserDetails buildPartial() {
        proto.UserDetailsOuterClass.UserDetails result = new proto.UserDetailsOuterClass.UserDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(proto.UserDetailsOuterClass.UserDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.accountNumber_ = accountNumber_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.dob_ = dob_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.accountType_ = accountType_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.accountSavings_ = accountSavings_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.UserDetailsOuterClass.UserDetails) {
          return mergeFrom((proto.UserDetailsOuterClass.UserDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.UserDetailsOuterClass.UserDetails other) {
        if (other == proto.UserDetailsOuterClass.UserDetails.getDefaultInstance()) return this;
        if (other.getAccountNumber() != 0) {
          setAccountNumber(other.getAccountNumber());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getDob().isEmpty()) {
          dob_ = other.dob_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getAccountType().isEmpty()) {
          accountType_ = other.accountType_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getAccountSavings() != 0D) {
          setAccountSavings(other.getAccountSavings());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                accountNumber_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                dob_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                accountType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 57: {
                accountSavings_ = input.readDouble();
                bitField0_ |= 0x00000040;
                break;
              } // case 57
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int accountNumber_ ;
      /**
       * <code>int32 accountNumber = 1;</code>
       * @return The accountNumber.
       */
      @java.lang.Override
      public int getAccountNumber() {
        return accountNumber_;
      }
      /**
       * <code>int32 accountNumber = 1;</code>
       * @param value The accountNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAccountNumber(int value) {

        accountNumber_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 accountNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 3;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 3;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 3;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      /**
       * <code>string dob = 4;</code>
       * @return The dob.
       */
      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dob = 4;</code>
       * @return The bytes for dob.
       */
      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dob = 4;</code>
       * @param value The dob to set.
       * @return This builder for chaining.
       */
      public Builder setDob(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dob_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string dob = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDob() {
        dob_ = getDefaultInstance().getDob();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string dob = 4;</code>
       * @param value The bytes for dob to set.
       * @return This builder for chaining.
       */
      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dob_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 5;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 5;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 5;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object accountType_ = "";
      /**
       * <code>string accountType = 6;</code>
       * @return The accountType.
       */
      public java.lang.String getAccountType() {
        java.lang.Object ref = accountType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accountType = 6;</code>
       * @return The bytes for accountType.
       */
      public com.google.protobuf.ByteString
          getAccountTypeBytes() {
        java.lang.Object ref = accountType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accountType = 6;</code>
       * @param value The accountType to set.
       * @return This builder for chaining.
       */
      public Builder setAccountType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        accountType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string accountType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountType() {
        accountType_ = getDefaultInstance().getAccountType();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string accountType = 6;</code>
       * @param value The bytes for accountType to set.
       * @return This builder for chaining.
       */
      public Builder setAccountTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        accountType_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private double accountSavings_ ;
      /**
       * <code>double accountSavings = 7;</code>
       * @return The accountSavings.
       */
      @java.lang.Override
      public double getAccountSavings() {
        return accountSavings_;
      }
      /**
       * <code>double accountSavings = 7;</code>
       * @param value The accountSavings to set.
       * @return This builder for chaining.
       */
      public Builder setAccountSavings(double value) {

        accountSavings_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>double accountSavings = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccountSavings() {
        bitField0_ = (bitField0_ & ~0x00000040);
        accountSavings_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.UserDetails)
    }

    // @@protoc_insertion_point(class_scope:proto.UserDetails)
    private static final proto.UserDetailsOuterClass.UserDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.UserDetailsOuterClass.UserDetails();
    }

    public static proto.UserDetailsOuterClass.UserDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserDetails>
        PARSER = new com.google.protobuf.AbstractParser<UserDetails>() {
      @java.lang.Override
      public UserDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.UserDetailsOuterClass.UserDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UserDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_UserDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user_details.proto\022\005proto\"\214\001\n\013UserDeta" +
      "ils\022\025\n\raccountNumber\030\001 \001(\005\022\014\n\004name\030\002 \001(\t" +
      "\022\017\n\007address\030\003 \001(\t\022\013\n\003dob\030\004 \001(\t\022\r\n\005email\030" +
      "\005 \001(\t\022\023\n\013accountType\030\006 \001(\t\022\026\n\016accountSav" +
      "ings\030\007 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_UserDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_UserDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_UserDetails_descriptor,
        new java.lang.String[] { "AccountNumber", "Name", "Address", "Dob", "Email", "AccountType", "AccountSavings", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
